### ISSUE TITLE
Arabic text is not aligned

### ISSUE THREAD

**Issue by umar052001** [KhawarSultan/Dal-copilot-Next-App#2]
![image](https://github.com/KhawarSultan/Dal-copilot-Next-App/assets/79453927/59462be3-9f0e-49d9-a061-7e666f6c4d97)
See the text alignment. It seems like it is aligned for english but not for arabic or any language which starts from right to left.
@KhawarSultan I have added todos to markdownconversion.tsx please fix this ASAP. #1

**Comment by KhawarSultan** [comment]
I've addressed the issue with the Arabic text alignment. The problem was that the text direction was not being set correctly, causing improper alignment for Arabic content and also fixes the font according to language.

![Text align issue fixed](https://github.com/KhawarSultan/Dal-copilot-Next-App/assets/110157121/c5f163d2-151c-4e0d-bc57-7afd3414dd0b)
